theme: jekyll-theme-minimal
title: Robotic Map Assessment and Standardisation
description: ECMR 2021 WORKSHOP
when: 2021-08-31
where: https://gather.town/app/yMxITlVsMIVtNDpx/goodmap2021
logo: logo/ws_logo.png
google_analytics: G-ZV82KHSGW1
